### ISSUE TITLE
Parse New ISPC Version String

### ISSUE THREAD

**Issue by cwfitzgerald** [Twinklebear/ispc-rs#10]
On Windows 1.14.1, I get the following output from `ispc --version`:

```
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.14.1 (build date Aug 28 2020, LLVM 10.0.1)
Supported Visual Studio versions: Visual Studio 2015 and later.
```

Notable changes include the added `Implicit` and a second `Intel(r)` in case you forgot who made the thing.

**Comment by cwfitzgerald** [comment]
Pardon this, I seem to have been using an old version of ispc-rs for some reason. I don't know why cargo selected 1.0.6 when I made this project 3 days ago.

**Comment by Twinklebear** [comment]
No worries!
