### ISSUE TITLE
Should this be checked in?

### ISSUE THREAD

**Issue by Jasper-Bekkers** [Twinklebear/ispc-rs#13]
https://github.com/Twinklebear/ispc-rs/blob/5188037512f45c0a6e88809ccb84b6e97dc86381/compile/src/lib.rs#L366

**Comment by Twinklebear** [comment]
This actually was a file that was output by `ispc -MMM` to output an ISPC file's dependencies, but I think it was a bug in ISPC. Checking back in the ISPC issue tracker it looks like this was fixed some time ago: https://github.com/ispc/ispc/issues/1419 , so I think it should be safe to remove now.

**Comment by Twinklebear** [comment]
Removed in https://github.com/Twinklebear/ispc-rs/commit/0de494f3eac4c5da0c0630296f34148f03f4d946
