### ISSUE TITLE
Should generate different rs binding for different platforms

### ISSUE THREAD

**Issue by Danielmelody** [Twinklebear/ispc-rs#16]
For example, in project [ispc-texcomp-rs](https://github.com/Danielmelody/ispc-texcomp-rs), the generated rs file contains target platform information.
For aarch64-apple-darwin
```rust
#[allow(non_camel_case_types,dead_code,non_upper_case_globals,non_snake_case,improper_ctypes)]
pub mod kernel {
/* automatically generated by rust-bindgen 0.59.2 */

pub const __WORDSIZE: u32 = 64;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_EXTSN: &[u8; 14usize] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
// etc...
```

For x86_64-unknown-linux-gnu:
```rust
#[allow(non_camel_case_types,dead_code,non_upper_case_globals,non_snake_case,improper_ctypes)]
pub mod kernel {
/* automatically generated by rust-bindgen 0.59.2 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
```

**Comment by Danielmelody** [comment]
This behavior is caused by bindgen, I 'm not sure whether it's their responsibility to handle this problem or ours.

**Comment by Twinklebear** [comment]
I don't think we'd need these in the generated .rs files, maybe there's a bindgen option to not include these system defines/values in the output .rs file?

**Comment by MarijnS95** [comment]
There are bindgen options to include/exclude certain values, but it's probably tricky to manage a so-called blocklist across many header targets, as they all have different values here.

Perhaps an idea is to instead use the allowlist feature and let the user set symbols that it wishes to include. Then bindgen includes only that symbol and everything transitively required, nothing more.

**Comment by Twinklebear** [comment]
It's now possible to filter these out by specifying the bindgen function allowlist, thanks to @MarijnS95 's PR: https://github.com/Twinklebear/ispc-rs/pull/20 . Once the last two #18 / #19 are merged I'll push an updated release out.

**Comment by MarijnS95** [comment]
I may not have fully clarified this in #20 but I don't think it fully fixes this issue (otherwise I might've added a `Fixes: #16`).

That PR gets rid of unused noise in the `bindgen` output - mainly what's been discussed here - but there may still be a possibility for platform-dependent types / signatures to end up in the output, as per the title. Pointers won't be a problem since Rust deals with those details (it's just an opaque raw ptr `*const`/`*mut` after all), but perhaps certain integer types or packing?

**Comment by Twinklebear** [comment]
I see, yeah having platform specific types in the function signatures could still be an issue, though I don't know if it should come up for the ISPC generated headers. I think the ISPC functions should just have regular C types and C-mappings of the ISPC types defined in the code, but shouldn't pick up platform specific things. If this does turn out to be an issue we can add some additional bindgen options(?) or look into what's needed to fix them.

**Comment by Twinklebear** [comment]
Ah although maybe we would need to add separate support for an "allowlist variables" kind of export if these are pulled in from some global declarations.

**Comment by MarijnS95** [comment]
I only see it being a problem with types like `int` which may have a different size depending on the target architecture (though it's `u32` on pretty much every popular arch still in use?).

>  Ah although maybe we would need to add separate support for an "allowlist variables" kind of export if these are pulled in from some global declarations.


Yeah, if `static` / `const` / `#define` is used. Good thinking, that may be useful to have as well.

**Comment by Twinklebear** [comment]
It looks like the allowlist_functions does help here though, I tested this out on the simple example and after adding `add_lists` as the only allowed function it did clean up the header, which previously had a lot of linux/posix defines or constants. We can add support for passing through more of these bindgen options though. For now I'll put out the allowlist add as a new release so it's available on crates

**Comment by MarijnS95** [comment]
Thanks for the release by the way! Note that GitHub can auto-generate release notes now too, they embed the PR links and contributors in a neat way (and you can of course customize the output, it's just markdown)!
