### ISSUE TITLE
Bindgen incompatibility with vector types in "C++" ISPC headers

### ISSUE THREAD

**Issue by MarijnS95** [Twinklebear/ispc-rs#27]
When `ispc` generates a header (`-h`) it mostly looks like C but _can_ contain C++ constructs like missing `struct` tags when using e.g. builtin types:

```c++
struct Test {
    uint<2> size;
};

export void use(uniform Test &test) {
}
```

This generates down to (preprocessor noise omitted for brevity):

```cpp
#ifdef _MSC_VER
__declspec( align(16) ) struct uint32_t2 { uint32_t v[2]; };
#else
struct uint32_t2 { uint32_t v[2]; } __attribute__ ((aligned(16)));
#endif

struct Test {
    uint32_t2  size; // error: must use 'struct' tag to refer to type 'uint32_t2'
};
```

With `bindgen` complaining about `error: must use 'struct' tag to refer to type 'uint32_t2'` annotated above. Note that `ispc` already went to lengths to flatten this type rather than using a template for the vector length!

Is this something that could/should be fixed in `ispc` (e.g. do they promise or is there a mode to let it emit a `C`-only header, which is unlikely given that ISPC code itself uses a bunch of C++ features), or worked around in `ispc-rs`? For example, for now I've hardcoded a:

```rust
writeln!(include_file, "typedef struct uint32_t2 uint32_t2;").unwrap();
```

In `generate_bindgen_header()` but that obviously isn't going to scale.

Any thoughts?

---

As a bonus I've used a C++ reference in the `export` function as structs are not allowed to be passed by value (and having a `uniform Test *uniform test` is just less convenient to deal with) and that generates to `extern void use(struct Test &test);` which isn't C-compliant either, but I guess this is more of a case of "if you intend your ISPC code to be used over a purely C FFI boundary, don't use C++ constructs in it" :grimacing:.

**Comment by Twinklebear** [comment]
This might be something that should be fixed in ISPC, the header files (as far as I remember) are supposed to be C-compatible, with now I guess the exception of if the code used references then that's it's own fault.

Adding some patching steps in ispc-rs's bindgen/code processing step seems like it'd be a bit fragile and tricky to get right, while having ISPC fix the header output to be C again would be an easier spot to fix it.

**Comment by MarijnS95** [comment]
Indeed, as noticed ISPC already goes out of its way to turn templated vectors into types, which it wouldn't have to do if this was intended for C++ only.

I'll raise this upstream (if not already open).

**Comment by MarijnS95** [comment]
Dumped my brain at https://github.com/ispc/ispc/issues/2650, will close this as "not planned" as we don't have to block on it here, there's nothing actionable for us.

**Comment by MarijnS95** [comment]
Already fixed upstream, let's wait for the next compiler drop :tada:
