### ISSUE TITLE
Make libclang/bindgen optioinal

### ISSUE THREAD

**Issue by emoon** [Twinklebear/ispc-rs#32]
Hi,

 First of all thanks for a great crate! For me the `libclang` dependency is a bit annoying (esp on windows) and I'm fine with just manually maintaining a "wrapper" rust file for calling into my ispc code so I wonder if it would be possible to have bindgen as an optional step instead?

**Comment by Twinklebear** [comment]
Hi @emoon , the `ispc-rs` crate can also be used in a separate compilation and runtime mode, which might achieve what you want. The `ispc-rs` crate is actually just a combination of two crates:

- [`ispc_compile`](https://crates.io/crates/ispc_compile): This crate provides the tooling to compile ISPC code to a library and generate the Rust bindings using bindgen. Only `ispc_compile` depends on bindgen, libclang, cc, ispc, etc.
- [`ispc_rt`](https://crates.io/crates/ispc_rt): This crate will look for an existing compiled ISPC library and simply link it, and import the Rust bindings into your Rust code so you can call it with the `ispc_module!` macro. `ispc_rt` is very lightweight, it just depends on `libc` and `num_cpus` (no bindgen/libclang)

So the way you could remove this dependency right now is described in the [Using Separate Compile and Runtime Crates](https://github.com/Twinklebear/ispc-rs?tab=readme-ov-file#using-the-separate-compile-and-runtime-crates) section, which is shown in the [simple example](https://github.com/Twinklebear/ispc-rs/tree/master/examples/simple).

The simple example works by compiling the ISPC code once, using the `ispc` feature flag (this will need `ispc_compile` and thus bindgen/libclang, etc.). Then for regular development or deployment you just use the `ispc_rt` crate to link your compiled ISPC library, and no longer need bindgen/libclang.

The downside of this route is that you need to compile the ISPC library for each platform you plan to deploy on and include it with your library or crate, but that may not be an issue depending on what your use case is.

**Comment by emoon** [comment]
I see. I will fiddle around a bit with it, but that will likely do the trick. Thanks!
