### ISSUE TITLE
ispc-binaries for CI

### ISSUE THREAD

**Issue by gnzlbg** [Twinklebear/ispc-rs#5]
I needed to use ISPC on travis-ci and appveyor for testing `packed_simd` and created a repo with the latest versions of the `x86_64` binaries for macos, windows, and linux. I couldn't find out exactly whether you were executing ISPC on CI but thought this might be useful to you. I won't use Docker images initially but might end up creating them eventually. 

The repo is here: https://github.com/gnzlbg/ispc-binaries

**Comment by Twinklebear** [comment]
Cool, thanks @gnzlbg ! Right now I don't actually run the ISPC compiler on CI, but it's something I hope to start doing
