### ISSUE TITLE
the current ispc-rs does not work with the new ispc v1.13

### ISSUE THREAD

**Issue by jvo203** [Twinklebear/ispc-rs#9]
thread 'main' panicked at 'Failed to parse ISPC version', /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/ispc_compile-1.0.8/src/lib.rs:124:39
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: ispc_compile::Config::new
  10: build_script_build::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
  16: __libc_start_main
  17: _start

Both Linux and macOS are equally affected.

**Comment by jvo203** [comment]
Apparently the version string has changed a lot in v1.13.

Here is the old format:
```Intel(r) SPMD Program Compiler (ispc), 1.12.0 (build commit 2a3fc60c1c60008d @ 20200402, LLVM 8.0.1)```

And this is the new one:
```Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.13.0 (build commit fa3e69687471c552 @ 20200424, LLVM 10.0.0)```

**Comment by Twinklebear** [comment]
Thanks for the bug report @jvo203 ! This should be quick to get fixed up, it looks like it's just a problem with parsing the version string

**Comment by Twinklebear** [comment]
This should be fixed in 4db1bd99b357ca483fd6d791bbf662c178140d06 , and is part of the version 1.0.9 `ispc-rs` and `ispc_compile` crate releases. Let me know if you run into any issues!

**Comment by jvo203** [comment]
Confirmed, works fine, thank you very much!
